version: '3.8'

services:
  mindgarden:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mindgarden
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - neo4j
    networks:
      - mindgarden-net

  neo4j:
    image: neo4j:5-community
    container_name: mindgarden-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password  # Default username/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - mindgarden-net

networks:
  mindgarden-net:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-logs: 